version: '3.7'

services:
  api:
    build: .
    ports:
      - '3333:3333'
    volumes:
      - '.:/app'
    environment:
      DB_CONNECTION: mysql
      DB_HOST: database
      DB_USER: root
      DB_PASSWORD: example
      DB_DATABASE: mesa
      DB_PORT: 3306
      HOST: '0.0.0.0'
      PORT: 3333
    command: adonis serve --dev
    depends_on:
      - database

  database:
    image: mysql:5
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mesa
